#!/usr/bin/env node
'use strict';

/**
 * 3D Text Animation Timeline Editor & Display
 * Editor:   http://localhost:5003/
 * Display:  http://localhost:5003/display
 *
 * npm install express ws opentype.js
 * node server.js
 */

const express = require('express');
const http    = require('http');
const wsLib   = require('ws');
const path    = require('path');
const fs      = require('fs');

const PORT   = 5003;
const BASE   = __dirname;
const SAVES  = path.join(BASE, 'saves');
const FONTS  = path.join(BASE, 'fonts');
const PUBLIC = path.join(BASE, 'public');

for (const d of [SAVES, FONTS]) if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });

const app    = express();
const server = http.createServer(app);
const WSS    = new wsLib.WebSocketServer({ server });

app.use(express.json({ limit: '50mb' }));
app.use('/fonts', express.static(FONTS));

// ── Serve Three.js r128 locally (no internet needed for OBS) ─────────────────
const THREE_BASE    = path.join(BASE, 'node_modules', 'three');
const PUBLIC_VENDOR = path.join(PUBLIC, 'vendor');

app.use('/vendor/three.min.js', (_, res) => {
  const nm    = path.join(THREE_BASE, 'build', 'three.min.js');
  const local = path.join(PUBLIC_VENDOR, 'three.min.js');
  res.sendFile(fs.existsSync(nm) ? nm : local);
});

// FontLoader.js + TextGeometry.js bundled in public/vendor/
app.use('/vendor', express.static(PUBLIC_VENDOR));

// Helvetiker typeface JSON — node_modules first, then public/vendor/fonts/
app.use('/vendor/fonts', (req, res, next) => {
  const nm = path.join(THREE_BASE, 'examples', 'fonts', req.path);
  if (fs.existsSync(nm)) return res.sendFile(nm);
  next();
});

app.use(express.static(PUBLIC));
app.get('/',        (_, res) => res.sendFile(path.join(PUBLIC, 'editor.html')));
app.get('/display', (_, res) => res.sendFile(path.join(PUBLIC, 'display.html')));

// ── Default state ─────────────────────────────────────────────────────────────
let appState = {
  tracks: [
    { id:1, enabled:true,  text:'BREAKING NEWS', outputText:'BREAKING NEWS', font:'helvetiker', color:'#ff4444', animation:'crashLandTop',   size:1.0, depth:0.30, yPos: 1.8, delay:   0, duration:0, bevel:true },
    { id:2, enabled:false, text:'Price Drop',    outputText:'Price Drop',    font:'helvetiker', color:'#ffcc00', animation:'zipInRight',     size:0.8, depth:0.25, yPos: 0.0, delay: 800, duration:0, bevel:true },
    { id:3, enabled:false, text:'At WalMarts',   outputText:'At WalMarts',   font:'helvetiker', color:'#44ff44', animation:'zipInSpin',      size:0.7, depth:0.20, yPos:-1.8, delay:1600, duration:0, bevel:true },
  ],
};

// ── WebSocket ─────────────────────────────────────────────────────────────────
function broadcast(obj) {
  const msg = JSON.stringify(obj);
  WSS.clients.forEach(c => c.readyState === wsLib.OPEN && c.send(msg));
}
WSS.on('connection', ws => {
  ws.send(JSON.stringify({ type: 'init', state: appState }));
});

// ── Font conversion helpers ───────────────────────────────────────────────────
const TYPEFACE_VERSION = 2;   // bump to force regeneration of all cached JSONs

function getFonts() {
  const list = [{ id: 'helvetiker', label: 'Helvetiker Regular (Built-in)', url: null }];
  try {
    for (const f of fs.readdirSync(FONTS)) {
      if (!f.endsWith('_typeface.json')) continue;
      const id = f.slice(0, -14);
      list.push({
        id,
        label: id.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
        url:   '/fonts/' + f,
      });
    }
  } catch (_) {}
  return list;
}

async function convertFonts() {
  let op;
  try { op = require('opentype.js'); } catch (_) {
    console.log('[fonts] opentype.js not installed — skipping conversion');
    return;
  }
  for (const f of fs.readdirSync(FONTS)) {
    if (!/\.(ttf|otf)$/i.test(f)) continue;
    const base = f.slice(0, f.lastIndexOf('.'));
    const out  = path.join(FONTS, base + '_typeface.json');

    // Regenerate if missing OR if generated by an older converter version
    if (fs.existsSync(out)) {
      try {
        const existing = JSON.parse(fs.readFileSync(out, 'utf8'));
        if (existing._v === TYPEFACE_VERSION) continue;   // up to date
        console.log('[fonts] Re-converting (outdated v' + (existing._v || 1) + '): ' + f);
      } catch (_) { /* corrupt JSON — reconvert */ }
    } else {
      console.log('[fonts] Converting: ' + f);
    }

    try {
      const font = op.loadSync(path.join(FONTS, f));
      fs.writeFileSync(out, JSON.stringify(fontToTypeface(font)));
      console.log('[fonts] OK ' + base + '_typeface.json');
    } catch (e) { console.error('[fonts] Error: ' + e.message); }
  }
}

/**
 * Convert an opentype.js Font to a Three.js typeface JSON.
 *
 * KEY FIX vs original: uses g.path.commands (Y-up font coordinates) instead
 * of g.getPath(0, 0, RES) which internally flips Y for screen/canvas space,
 * causing upside-down text in Three.js TextGeometry.
 */
function fontToTypeface(font) {
  const RES = 1000, SC = RES / font.unitsPerEm, R = n => Math.round(n);
  const glyphs = {};

  for (let i = 0; i < font.glyphs.length; i++) {
    const g = font.glyphs.get(i);
    if (!g.unicode) continue;
    const ch   = String.fromCodePoint(g.unicode);
    const cmds = (g.path && g.path.commands) ? g.path.commands : [];
    let o = '';
    for (const c of cmds) {
      if      (c.type === 'M') o += 'm '  + R(c.x  * SC) + ' ' + R(c.y  * SC) + ' ';
      else if (c.type === 'L') o += 'l '  + R(c.x  * SC) + ' ' + R(c.y  * SC) + ' ';
      else if (c.type === 'Q') o += 'q '  + R(c.x1 * SC) + ' ' + R(c.y1 * SC) + ' '
                                          + R(c.x  * SC) + ' ' + R(c.y  * SC) + ' ';
      else if (c.type === 'C') o += 'b '  + R(c.x1 * SC) + ' ' + R(c.y1 * SC) + ' '
                                          + R(c.x2 * SC) + ' ' + R(c.y2 * SC) + ' '
                                          + R(c.x  * SC) + ' ' + R(c.y  * SC) + ' ';
      else if (c.type === 'Z') o += 'z ';
    }
    glyphs[ch] = {
      ha:    R(g.advanceWidth  * SC),
      x_min: R((g.xMin || 0)  * SC),
      x_max: R((g.xMax || 0)  * SC),
      o:     o.trim(),
    };
  }

  const head = font.tables.head || {}, post = font.tables.post || {};
  return {
    _v:      TYPEFACE_VERSION,
    glyphs,
    familyName:         (font.names.fontFamily && font.names.fontFamily.en) || 'Custom',
    ascender:           R(font.ascender  * SC),
    descender:          R(font.descender * SC),
    underlinePosition:  R((post.underlinePosition  || -100) * SC),
    underlineThickness: R((post.underlineThickness ||   50) * SC),
    boundingBox: {
      yMin: R((head.yMin || 0)    * SC),
      xMin: R((head.xMin || 0)    * SC),
      yMax: R((head.yMax || 1000) * SC),
      xMax: R((head.xMax || 1000) * SC),
    },
    resolution:                RES,
    original_font_information: font.names,
  };
}

// ── REST API ──────────────────────────────────────────────────────────────────
app.get('/api/state',  (_, res) => res.json(appState));
app.post('/api/state', (req, res) => {
  appState = req.body;
  broadcast({ type: 'state', state: appState, autoPlay: true });
  res.json({ ok: true });
});

app.post('/api/trigger', (_, res) => { broadcast({ type: 'trigger' }); res.json({ ok: true }); });
app.post('/api/reset',   (_, res) => { broadcast({ type: 'reset'   }); res.json({ ok: true }); });

app.get('/api/fonts',      async (_, res) => { await convertFonts(); res.json(getFonts()); });
app.get('/api/scan-fonts', async (_, res) => { await convertFonts(); res.json(getFonts()); });

app.get('/api/saves', (_, res) =>
  res.json(fs.readdirSync(SAVES).filter(f => f.endsWith('.json')).map(f => f.slice(0, -5))));

app.get('/api/saves/:n', (req, res) => {
  const p = path.join(SAVES, req.params.n + '.json');
  fs.existsSync(p) ? res.json(JSON.parse(fs.readFileSync(p, 'utf8'))) : res.status(404).json({ error: 'Not found' });
});
app.post('/api/saves/:n', (req, res) => {
  fs.writeFileSync(path.join(SAVES, req.params.n + '.json'), JSON.stringify(req.body, null, 2));
  res.json({ ok: true });
});
app.delete('/api/saves/:n', (req, res) => {
  const p = path.join(SAVES, req.params.n + '.json');
  if (fs.existsSync(p)) fs.unlinkSync(p);
  res.json({ ok: true });
});

// ── Ensure Helvetiker JSON is available locally ───────────────────────────────
async function ensureHelvetiker() {
  const dest = path.join(PUBLIC_VENDOR, 'fonts', 'helvetiker_regular.typeface.json');
  if (fs.existsSync(dest)) return;
  const nm = path.join(THREE_BASE, 'examples', 'fonts', 'helvetiker_regular.typeface.json');
  if (fs.existsSync(nm)) {
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(nm, dest);
    console.log('[fonts] Copied Helvetiker from node_modules');
    return;
  }
  console.log('[fonts] Downloading Helvetiker from CDN...');
  try {
    const https = require('https');
    const url   = 'https://threejs.org/examples/fonts/helvetiker_regular.typeface.json';
    await new Promise((resolve, reject) => {
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      const file = fs.createWriteStream(dest);
      https.get(url, res => { res.pipe(file); file.on('finish', () => { file.close(); resolve(); }); })
           .on('error', e => { fs.unlink(dest, () => {}); reject(e); });
    });
    console.log('[fonts] Helvetiker downloaded OK');
  } catch (e) {
    console.warn('[fonts] Could not download Helvetiker:', e.message);
  }
}

// ── Start ─────────────────────────────────────────────────────────────────────
server.listen(PORT, async () => {
  console.log('\n3D Title Editor');
  console.log('  Editor:  http://localhost:' + PORT + '/');
  console.log('  Display: http://localhost:' + PORT + '/display');
  console.log('  Fonts:   ' + FONTS);
  console.log('  Saves:   ' + SAVES + '\n');
  await ensureHelvetiker();
  await convertFonts();   // auto-reconverts any font whose JSON is outdated
});
